nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        origin_regex: true

    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            expose_headers: ['Authorization']
            max_age: 3600
